### ISSUE TITLE
Echelon energy consumption not showing on HA energy dashboard

### ISSUE THREAD

**Issue by klausnitzer** [jnxxx/homeassistant-dabblerdk_powermeterreader#10]
Hi there my issue is that "Echelon energy consumption" is showing just fine on a entities card but not an the HA Energy dashboard. I can find the entity in the dropdown under "Configure grid consumption" but no values are shown on the dashboard.

Echelon integration installed via hacs v1.0.4

**Comment by AMajland** [comment]
Possible due to a missing device_class energy ?

        unit_of_measurement: kWh
        device_class: energy
        state_class: total_increasing

**Comment by klausnitzer** [comment]
Yes looks like all is set:

sensor.echelon_energy_consumption
```
   state_class: total_increasing
   unit_of_measurement: kWh
   device_class: energy
   icon: mdi:home-import-outline
   friendly_name: Echelon energy consumption
```

**Comment by jnxxx** [comment]
Any chance you have just added the sensor?
The Energy dashboard shows deltas, so it takes a little while until it appears.

**Comment by klausnitzer** [comment]
No the sensor is added long time ago.
It looks like i don't have historical data on the echelon_energy_consumption
````
state_class: total_increasing
unit_of_measurement: kWh
device_class: energy
icon: mdi:home-import-outline
friendly_name: Echelon energy consumption
````
![image](https://github.com/jnxxx/homeassistant-dabblerdk_powermeterreader/assets/11440152/4a9ba370-ca22-489d-9fef-b174a2cb97b1)
in comparison to a shelly-plug-s-kontor energy
````
state_class: total_increasing
unit_of_measurement: kWh
device_class: energy
friendly_name: shelly-plug-s-kontor energy
````

![image](https://github.com/jnxxx/homeassistant-dabblerdk_powermeterreader/assets/11440152/e09c7500-ca34-453f-a5ca-b80b6f9591d6)
 

I am using the InfluxDB integration could the problem be there?

**Comment by jnxxx** [comment]
I have no experience with InfluxDB. SQLite still works well for me.

Does the value shown, ~61365,8, reflect the value shown on the meter?
And does it get updated when the meter value changes?
If so, I think it is something internal in HA.
Any chance you have configured the [`Recorder`](https://www.home-assistant.io/integrations/recorder/) component? Check excludes and includes.

If it does not update the value and it is different than the one on the meter:
Try to enable debug logging.
Which scan interval do you use? Click `Configure` from the Integrations page. Default is 300 (5 minutes), I use 60 seconds.

**Comment by klausnitzer** [comment]
Sorry for not returning. Setting the scan interval to 60 seconds did the job. It is working now. Thank you for your help.
