### ISSUE TITLE
Electrical constant names used in intergration are deprecated as of HA Core 2025.1

### ISSUE THREAD

**Issue by mbagge** [jnxxx/homeassistant-dabblerdk_powermeterreader#12]
Suddenly 2025 is all over us and we cannot have this fine integration stop working.

Logger: homeassistant.const
Kilde: helpers/deprecation.py:205
Første forekomst: 10.54.51 (4 forekomster)
Senest logget: 10.54.51

    ELECTRIC_POTENTIAL_VOLT was used from dabblerdk_powermeterreader, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfElectricPotential.VOLT instead, please create a bug report at https://github.com/jnxxx/homeassistant-dabblerdk_powermeterreader/issues
    ELECTRIC_CURRENT_AMPERE was used from dabblerdk_powermeterreader, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfElectricCurrent.AMPERE instead, please create a bug report at https://github.com/jnxxx/homeassistant-dabblerdk_powermeterreader/issues
    POWER_WATT was used from dabblerdk_powermeterreader, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfPower.WATT instead, please create a bug report at https://github.com/jnxxx/homeassistant-dabblerdk_powermeterreader/issues
    FREQUENCY_HERTZ was used from dabblerdk_powermeterreader, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfFrequency.HERTZ instead, please create a bug report at https://github.com/jnxxx/homeassistant-dabblerdk_powermeterreader/issues

**Comment by deepansteven** [comment]
Agree :)

**Comment by jnxxx** [comment]
Sure.
I will publish a new version before that time.

**Comment by jnxxx** [comment]
v1.0.5 that should address this has now been released.
