### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by grawsom** [jnxxx/homeassistant-dabblerdk_powermeterreader#5]
Have just installed/configured HW from dabbler, and integrated your stuff in HA.
I just have 1 question.
How to get your "Energy dashboard" in HA as shown in your Readme.

**Comment by jnxxx** [comment]
You need to configure the Energy dashboard first.
You'll find it in: `Settings` > `Dashboards` > `Energy` > Under grid consumption: `Add Consumption`

Then select the right entity. Possibly "Echelon energy consumption", if you used the default meter name.
