### ISSUE TITLE
Fwd_Act_Wh changed too much

### ISSUE THREAD

**Issue by Labo322** [jnxxx/homeassistant-dabblerdk_powermeterreader#9]
Hvis jeg starter opladningen af min el bil samtidig med at opvaskemaskinen kører stopper integrationen. 

Bilen tager i gennemsnit 4-5 timer at oplade, opvaskeren kører omkring 1.5time. - starter begge omkring kl. 00:30

L1 current stiger fra ca. 1A til ca. 26A indenfor 20min

Integrationen stopper med at give målinger, også selv om begge dele forlængst er stoppet. 
Som jeg læser dit indlæg hos dabbler, burde den ignorere den høje måling i en time inden den acceptere den, det virker som det ikke sker.

Modul firmware: [NES MEP, version: Dec 23 2022 11:07:41]

Hvis integrationen genindlæses, virker det igen indtil næste gang bilen skal lades.

Fra HA log:

Logger: custom_components.dabblerdk_powermeterreader.meter.meter
Source: custom_components/dabblerdk_powermeterreader/meter/meter.py:49
Integration: Dabbler.dk reader for Echelon/NES smart power meter (documentation, issues)
First occurred: 00.37.21 (97 occurrences)
Last logged: 08.37.21

Fwd_Act_Wh changed too much (23441), sticking to previous values
Fwd_Act_Wh changed too much (23453), sticking to previous values
Fwd_Act_Wh changed too much (23466), sticking to previous values
Fwd_Act_Wh changed too much (23478), sticking to previous values
Fwd_Act_Wh changed too much (23485), sticking to previous values

**Comment by jnxxx** [comment]
Kan du ikke trykke `Load full logs` også finde log entries der, således at der kommer tider med?

26A på én fase?
Det er godt nok meget...

Hvor ofte opdaterer du? (Scan interval i `Configure` på integrationen)
Hvis denne står højt, så prøv som en hurtig workaround at sætte denne ned til f.eks. 60 sekunder.

**Comment by allanhvam** [comment]
Jeg oplever samme problem ved ladning af elbil.

Mit opdaterings interval er 300 sekunder.

**Comment by Labo322** [comment]
De 26A kom også lidt bag på mig, det er kun på L1.
L2 og L3 ligger på omkring 16A
Der er på L1 et grundforbrug på ca. 1A, dertil kommer opvasker på ca. 9A også billaderen på 16A

Scan interval er 300 sekunder

Problemet kommer kun når opvaskemaskinen kører, hvis jeg lader bilen uden den kører, er der ingen problemer.

[Logs.txt](https://github.com/jnxxx/homeassistant-dabblerdk_powermeterreader/files/10833415/Logs.txt)

**Comment by jnxxx** [comment]
Jeg kan godt se den ryger lige over grænsen på 1000 Wh imellem to målinger.
Jeg har nu justeret lidt på grænsen, således at tiden imellem målingerne tages i betragtning.

Der kommer en opdatering ud senere i dag.
Meld gerne tilbage om det af hjælper problemet.

**Comment by Labo322** [comment]
Jeg har ingen problemer længere. 
Tak for hurtig respons!
